version: "3.6"

services:
  txnotifier:
    image: makevoid/bitcoin-tx-notifier
    ports:
      - 80:80
    build:
      context: .
    environment:
      - ADDRESSES=3N3RXbpGHn6bfvcE2nEYbvGHVPorVWgkeQ
      # you can use a list of comma separated addresses
